stages:
  - build
  - publish

variables:
  APP_NAME: leg-auth
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

build:
  image: gradle:jdk17
  stage: build
  script:
    - gradle bootJar
  artifacts:
    paths:
      - build/libs/*.jar
  only:
    - prod

publish:
  stage: publish
  image:
    name: docker:latest
  services:
    - docker:19-dind
  before_script:
    - apk add --no-cache curl jq python3 py3-pip
    - pip install awscli --break-system-packages
    - aws ecr get-login-password | docker login --username AWS --password-stdin $ECR_REGISTRY
  script:
    - docker build -t $ECR_REGISTRY/$APP_NAME:$CI_PIPELINE_IID .
    - docker push $ECR_REGISTRY/$APP_NAME:$CI_PIPELINE_IID
  only:
    - prod