spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

test-accounts: ${TEST_ACCOUNTS}
