spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}

springdoc:
  api-docs:
    enabled: false

#AWS_S3_BUCKET: leg-prod-images
#AWS_IMAGE_HOST: https://image.leteatgo.co.kr
